### ISSUE TITLE
Safari Feather Bug

### ISSUE THREAD

**Issue by MoralesJonathan** [HackFSU/HackFSU-Preview#10]
Bug in Safari that distorts the feather SVG when seen on a smaller screen instead of hiding the feather.

![image](https://user-images.githubusercontent.com/17746797/28195296-61e8a98a-6817-11e7-8177-745f72e19dcf.png)

**Comment by andrewsosa** [comment]
Fixed in eded4b2c05e88dcb6c5c845ae51a712a3b394c40 as part of #19.
