### ISSUE TITLE
Meta Tag Description Change

### ISSUE THREAD

**Issue by justineoliver97** [HackFSU/HackFSU-Preview#12]
Can we change the meta tag to say:

"HackFSU is back and bolder than ever! Join us in our 5th year as we work with FAMU for 36 hours of collaborating, creating, and celebrating. From aspiring developers to designers, and everything between, students will have the opportunity to build bigger, better, and bolder projects.”

I want to make sure that everyone knows we will be working with FAMU this year.

**Comment by ghost** [comment]
How about:
> HackFSU is back and bolder than ever!  Join FSU and FAMU on our 5th birthday for 36 hours of collaborating, creating, and celebrating.  From aspiring developers to designers, and everything between, students will have the opportunity to build bigger, better, and bolder projects.

It's syntactically better, and it makes FAMU part of "us" instead of being implied as separate

**Comment by justineoliver97** [comment]
That works!
Also, can we make it “in-between” instead of just “between”.

**Comment by ghost** [comment]
@justineoliver97 agreed

Also, the end could be:
> HackFSU is back and bolder than ever! Join FSU and FAMU on our 5th birthday for 36 hours of collaborating, creating, and celebrating. _From aspiring developers to designers, and everything in between, come together to build bigger, to get better, to **be** bolder._

**Comment by justineoliver97** [comment]
Okay, let’s make the end part "From aspiring developers to designers, and everything in between, come together to build bigger, get better, and be bolder."

**Comment by andrewsosa** [comment]
Fixed via #28
