### ISSUE TITLE
Content on mobile not centered.

### ISSUE THREAD

**Issue by MoralesJonathan** [HackFSU/HackFSU-Preview#17]
Content inside of the container is not centered. Since there is no scaling happening, the content starting from the right begins to get cut off. Leaving more padding on the left than on the right. Here's an example with `overflow: auto;` added.

![d472dd4a-e6b7-4b2e-aac8-4b8cf5150ba9](https://user-images.githubusercontent.com/17746797/28223560-e4c748c0-6899-11e7-87c5-87427ba4a163.GIF)

**Comment by andrewsosa** [comment]
Fixed in eded4b2c05e88dcb6c5c845ae51a712a3b394c40 as part of #19
