### ISSUE TITLE
Pop up keyboard breaks mobile layout

### ISSUE THREAD

**Issue by ghost** [HackFSU/HackFSU-Preview#2]
When clicking the sign-up link and attempting to type my email address, the keyboard pop-up breaks the layout, causing elements to overlap as shown below.

![screenshot_2017-07-09-18-20-46](https://user-images.githubusercontent.com/14112725/27998121-d8ef08b2-64d4-11e7-9342-cd49d23e6863.png)

**Comment by andrewsosa** [comment]
Fixed, see commit 24d36d1f2a0c5f8251a45a9a7a433d5204ebae2a.
