### ISSUE TITLE
Font loading issue on Google chrome for android

### ISSUE THREAD

**Issue by ghost** [HackFSU/HackFSU-Preview#3]
![screenshot_2017-07-09-18-25-34](https://user-images.githubusercontent.com/14112725/27998114-9094da24-64d4-11e7-9fd9-035c4e888151.png)

Font may not be linked in the right place, I know some browsers require import statements to come first in the stylesheet.

**Comment by andrewsosa** [comment]
Fixed, commit cfdbe3fd968dd466f714958e18b44c461e32510d.
