### ISSUE TITLE
IE Feather bug

### ISSUE THREAD

**Issue by MoralesJonathan** [HackFSU/HackFSU-Preview#9]
Bug where IE renders the feather SVG huge and hides all the content behind it.
![image](https://user-images.githubusercontent.com/17746797/28195250-26839d1e-6817-11e7-8106-dc54c9b92166.png)

**Comment by ghost** [comment]
IE is notorious for not respecting SVG sizing, it may be a viewbox issue.

**Comment by andrewsosa** [comment]
@jonmorazav could we verify if this is still occuring after #19? Should be on the live site.

**Comment by andrewsosa** [comment]
IE still has some problems, one of which is the feature now being compressed. 

![jdkmir0ubr](https://user-images.githubusercontent.com/2829058/28360081-68054a38-6c42-11e7-8ec7-7fc5d6257fe5.gif)

**Comment by andrewsosa** [comment]
- [ ] Two scrollbars
- [ ] Compressed feather
- [ ] Code of conduct is shunted offscreen, the columns are extra tall for some reason

**Comment by andrewsosa** [comment]
Edge also has the CoC offscreen, but neither of the other two.

**Comment by andrewsosa** [comment]
Dealt with via #26 – we add a popup telling users to not use IE.
